include Makefile.dirs.vars
include Makefile.cmd.vars

$(BUILD_DIR)/.init.dirs:
	$(MKDIR) $(BINS_DIR)
	$(MKDIR) $(LIBS_DIR)
	$(MKDIR) $(OBJS_DIR)
	$(MKDIR) $(OBJS_DIR)/$(SRCS_DIR)
	$(MKDIR) $(OBJS_DIR)/$(UNIT_TEST_DIR)
	$(MKDIR) $(OBJS_DIR)/$(PERFORMANCE_TEST_DIR)
	$(MKDIR) $(RUN_DIR)
	touch $(BUILD_DIR)/.init

init: $(BUILD_DIR)/.init.dirs

