include Makefile.dirs.vars
include Makefile.srcs.vars
include Makefile.paths.vars


DEPEND_FILE=$(MAKEFILES_DIR)/.depend

$(DEPEND_FILE): $(ALL_SRCS)
	@touch $(DEPEND_FILE)
	makedepend  -p$(OBJS_DIR)/ $(LOCAL_INC_PATHS) -f $(DEPEND_FILE) $^

depend: $(DEPEND_FILE)
